### PR TITLE
Er and schema

### PR DESCRIPTION
**Pull request by ImShubhK**
Here I am adding the Er diagram and the schema of the database.

Here is the video [link](https://vimeo.com/867629531?share=copy).

Er: 
Screenshot 2023-09-22 at 12 02 32 PM
Schema:
Screenshot 2023-09-25 at 10 10 36 AM

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
1. ERD diagram and explanation is fine.
2. Schema diagram is not meeting the expectations, there is lack of connections between many tables, and there is no proper connection shown for foreign key in appropriate tables connected to the primary key of respective tables.

**Comment by ImShubhK** [comment]
So, Here is the video [Link](https://vimeo.com/867908609/eedeb50b76?share=copy) for the explanation of the Foreign Key.

Here is the Updated schema, Where I added the foreign key and established the necessary connections between the tables.

Screenshot 2023-09-25 at 5 49 04 PM

**Comment by PRASANNAPATHI** [comment]
In updated schema, 
User table should have RoleId foreign key, and Role table should not have userId foreign key.
Cart table - no proper difference between itemId and ProductId, where the ItemId came from?
Order, Order Item, Cart - are not connected in proper way.

**Comment by ImShubhK** [comment]
I updated the schema removed the user_id from the Role table and established a proper connection between the order and cart. I have changed item_id to cart_item_id.
image

**Comment by PRASANNAPATHI** [comment]
1.Order_item table should have only, a)Project_id (as foreign key), b)quantity and c)Order_id(as foreing key)
2.Order_id table should not have order_item_id, Instead, Order_id should be connected to Order_item table as mentioned in 1st statement.
3. The about two statements are also applicable for Cart and Cart_item tables.

This is how, it can be done properly.

**Comment by ImShubhK** [comment]
I updated the changes according to your suggestion.
image
image

**Comment by PRASANNAPATHI** [comment]
Yes Shubham,
It looks fine now.

Please, merge it now.

**Pull request merged**
